blank_issues_enabled: false
contact_links:
  - name: â“ Questions
    url: https://github.com/RapidAI/Knowledge-QA-LLM/discussions/categories/q-a
    about: Please use the community forum for help and questions regarding Knowledge-QA-LLM Docs
  - name: ğŸ’¡ Feature requests and ideas
    url: https://github.com/RapidAI/Knowledge-QA-LLM/discussions/new?category=feature-requests
    about: Please vote for and post new feature ideas in the community forum
  - name: ğŸ“– Documentation
    url: https://rapidai.github.io/Knowledge-QA-LLM/
    about: A great place to find instructions and answers on how to run your custom Knowledge-QA-LLM.
