blank_issues_enabled: false
contact_links:
  - name: â“ Questions
    url: https://github.com/RapidAI/RapidRAG/discussions/categories/q-a
    about: Please use the community forum for help and questions regarding RapidRAG Docs
  - name: ğŸ’¡ Feature requests and ideas
    url: https://github.com/RapidAI/RapidRAG/discussions/new?category=feature-requests
    about: Please vote for and post new feature ideas in the community forum
  - name: ğŸ“– Documentation
    url: https://rapidai.github.io/RapidRAG/
    about: A great place to find instructions and answers on how to run your custom RapidRAG.
